version: "3.7"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Can set another path 
      - ./mysql/data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST:-mysql}
      PMA_PORT: ${MYSQL_PORT:-3306}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}

  # web-server
  proxy:
    environment:
      - ACME_AGREE=true
    build:
      context: ./caddy
    volumes:
      - ./caddy/${CADDY_FILE:-Caddyfile}:/etc/caddy/Caddyfile

  
  # mail-server
  mail:
    image: mailhog/mailhog


  nextjs-nexus:
    tty: true
    build:
      context: ./nextjs-nexus
      network: ${NETWORK_NAME:-prisma-cms-default}
      args: 
        - SITE=nextjs-nexus
        - DATABASE_URL=${NEXTJS_DATABASE_URL}
        - SUDO_PASSWORD=${NEXTJS_SUDO_PASSWORD}
        - PWA=${PWA}
        - ENV_MODE=development
    volumes:
      - ./nextjs-nexus/shared:/www/nextjs-nexus/shared
      - ./nextjs-nexus/uploads:/www/nextjs-nexus/uploads
    env_file: 
      - .env
    environment: 
      - DATABASE_URL=${NEXTJS_DATABASE_URL}
      - SUDO_PASSWORD=${NEXTJS_SUDO_PASSWORD}
      - ENV_MODE=development
    command: bash -c "yarn dev"


  rtcmultyconnection:
    tty: true
    build:
      context: ./rtcmultyconnection
    command: yarn --ignore-engines start

  coturn:
    build:
      context: ./coturn
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf
    ports:
      ## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      # - "80:80"
      # - "80:80/udp"
      ## STUN/TURN SSL
      # - "5349:5349"
      # - "5349:5349/udp"
      # - "5350:5350"
      # - "5350:5350/udp"
      # - "443:443"
      # - "443:443/udp"
      # Relay Ports
      #      - "49152-65535:49152-65535"
      #      - "49152-65535:49152-65535/udp"
      

# volumes:
#   mysql:

networks:
  default:
    name: ${NETWORK_NAME:-prisma-cms-default}
