version: "3.7"

services:

  mysql:
    restart: always

  pma:
    restart: always

  proxy:
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443

  nextjs-nexus:
    restart: always
    environment: 
      ENV_MODE: production
    build:
      args: 
        - ENV_MODE=production
    command: npm run start

  rtcmultyconnection:
    restart: always

  coturn:
    restart: always
